# Generated by Django 6.0.5 on 2026-06-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✔️', help_text='Emoji yoki belgi (masalan: 🚌, 🍽, ✨)', max_length=10)),
                ('label', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='tours.tour')),
            ],
        ),
    ]
