# Generated by Django 6.0.5 on 2026-06-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='full_time',
            new_name='full_name',
        ),
    ]
