# Generated by Django 6.0.5 on 2026-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_full_time_passenger_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='use_discount',
            field=models.BooleanField(default=False),
        ),
    ]
